language: python
python:
- '2.6'
- '2.7'
script:
- make test
install:
- pip install .
deploy:
  provider: pypi
  user: d2s3admin
  password:
    secure: 2QGH0ZCrBk9kKSRlJPji53rMRL8KgFGxk+5uXM9JhOfbcLMJ17ohYJwe8ha2sq5aZAIDb/X+d0wepLvYDio+ko7mPNsAh6MraBm+0s19zZ9VNdf2HrveFcLPEsUf8sYUlOh5UXu83AKaFhNJMTaUnA7xUUFcEfegsXJIGW/49oyb3ZDTkZgKT2WbonaY2Ct4KTxQyWXouLy9ZDYqVeC2imIXRg3ErNcpnrFSptlbtOcmyRoCeF2q23JtUYKDz21hSOqaE7z2mMbWbSNNcPw8ArJoGJMhLRVYRRYCRIRW1oDVtsqLFaG9S5v3M15RmwoZZcHtfHIkaJwm7DETBmDT0sEqqxTS2LRbQEtJ255dYDzY+cg1h/PebuUZrLh8YEU0HgYawVgO2EZ7b/B7EdtrtfFIZdgE3KGMDuV29T1z3ELqjY84xrWrv5oL0Z1D2OuYZjUGxUcHalhrw6d0g68mMwQ9Q157AmR/aG50rzpGIvLqG4rFDjeNBV8EGwshPsGdH2N5uIQ+BfEQqpXC7hMLvAVc6aaTWFahzGCUUwBzemUj2tHfXFuThrWCuj3xYxXs1ODREVNtxAyc1rQZL8rmdaY1gv7ih9QbJEN+LoJ7To3iHvdoa0E8G0yv8LtvV3VlxFLkr5sthjog29PjZHb0fhr7J818KaKq2zpa3b/zvLA=
  on:
    tags: true
    repo: EnlightNS/enlightns-cli
    all_branches: true
notifications:
  email: false
  slack:
    secure: C1LGF/oU/NbgZgPCOMQeh5A7AAWrL3s6QX/FdUWw91QjLfBLJYIyEDcWIw1N8KeiHsLelfUQh9feGJfQVHWjjmn4auNbbykFQC5N9BrKvD5F8IE61ck3YSck7leqNpB/GnNybbqHNJD2X6/su+oCBOhyk60XdFbBMIWTlch4cJRWbzymDFM86xIkR5pJhGZXmbj2RlXsrPPSoFKgHOjrfLQP0bACKhZnymkvMPQlm0CWIOeX6prv/8BAsAgEUOqnXCr1UQUVKcbxmDEQ1KCpyzH3jIl1aXG/wh/cp0uF+urYEfpTRDsbl21MiztMTJcqbHgC1fhhkNGhtNvCBAmNc3JpavF+iI4gHuUSRJa+tPGsPndMlNsqu3xwJ0gW2vGj8admdHEWIkK3P2GkqB8ZVK673mLYSo4c1beOU6kr55Tq2MPhSg+znq0cYN3/gDCoBqVmedA4qeG1NrBpvvHodBfRt6AM8Gyn1uQme+NXShf2ovNP0o3lGKyLx0b9vsnbf8bUH/a7wc0CeDTPWh5YNB+aXN/1mSnGmUS/Peu0vIuvcxe8ZXJfXjMFlFcyV0p/SyI5B0BGoIThgODZCqQBZiECoHfJvXv0Cvxsy4kLrdZssNpNVqAYGtQebnU486Y3Nx5aYKbnRFFZUMqx7AJ2nhG+FkNVkI7QAhtxo2ujgU0=
