language: python
python:
- '3.6'
script:
- make test
install:
- pip install .
deploy:
  provider: pypi
  user: "__token__"
  on:
    tags: true
    repo: EnlightNS/enlightns-cli
  password:
    secure: xLx+0abozggmQfbOM1dNThI09f9eXND5/ZsRRPN1wsjyZhRVENqskXut8hHj9zIwX/rFCIBWkwsXEVk06x3m2ZcKDaANGsgNw3B6DtetBf7uNNIw5tbu1myE+3VG4vsKW8OWae+A7dxptnEUlLr48hTb6gfW9Su/siXAizrq/vzVEHM01OSwGf5bkKErD0yEBHRYEDvYFF5tcMdWdsbCUMrXOzQurA6GpkwQUqGChySCgGmEKg74rBpSHq8r6mpOVaFiQYGMyoAxY+5saB6rVYknkdrfZNNg1fmF1gujbDEQUndyTbvcsyBY6K3CA/wRlYKQh9MJTsVq5Qs6eEzTpZ/FJaYmcY78HSSX81oOScVGDniJ6YA2PZVwgAykxHPD1kgXtNlboPgaTCx0yQ/gmJfOPyS7MVddnxL/lcNLsbgw4xgtGvSjnclCaujzmw231q5hzGMyckjT9zO4L/Ho+ARugxgMIQMuE+ko2zbAKLtXGuRIw/ue7LUOd78VzkFH2FPnyqPU4goRBkhmTwNe1Loq0fp/vkUVNSJGPO6wUOu7sPcoSOE54FHiwqq1YnJbImjiUBk2iynhpPA6X3VaKKQloNG9TVSJh6Gs2HWTdSy/BhLhXqokkbibUssdRHaL/ypd6lHcGiAMm/sVBE6+PZr+iXNiCZTPyeXe70GoAuY=
notifications:
  email: false
  slack:
    secure: Tzy8g7cNpJ5Nzgpyx8AhP8IljJAL7eggkXipRSYFuw9z7XOpitmr6S7YSaKD8FuTjnSdgFemvCvc4tQB5EICKU7CxD7fTDCveuxNoXAaDaXNZfd0EuHSM81G5EM+5DAeYTMnlnzy/wWQHWSvpTcAJl4Qzqp5DjVpscTW5Uoo6psMV6/FMLpjmID9PihiBYi0eiDPL7pK7VbSaNQ8w+e+KCzf5M+ZTjuDBJe7OMcQFhnjPW+w6J4p38BAYzXfEnKzO//DzVnoPKVHEge6jEqW3DoloVyF5T6vS734Ffn63lw3JSfV9LqfI7domAG9v/YuE1My9wgOkraWEpMRO/hrFLTnza2LGrJHvje+YsSI5UuNN+Sk2YBQtwvG4hwPGIilCeH5MOAb5yZctJqAmLzTyhboz/9ub+upDEhMK4OqH9kDsZEGzSK0JpS60De5mCM7yOOeUaFI0CAOk10YjrvGFW5NJY1LVejEAtW4SFHM6vNwT2hPfCrg4Zkcl/Fac4Lh8M/uURsuERciZcQItmOlVt86UhTf/4Pxp++q4zrGOBIOjUQN8iwva84Z3qnPxXyvlOioOyphuKDf0HffsR5kdfT/CbNHIv+7GfBG1zlA8TiazhUGa82REAomMFYedN1ped8SlgfK/aom6pPqIGuweVl3HzS4cLc9z2SBwOLNOFQ=
