language: python
python:
- '2.7'
script:
- make test
install:
- pip install .
deploy:
  provider: pypi
  user: d2s3admin
  password:
    secure: EL3HEzXGj/Tb4HxvmerIzSMAAMFPpRmOd39n7c1XEhXmaYzv4cJoc41B6QOcZqEKqG0AMzXEh7S/mCuqiANedBzw8nP1OIN4K/K6c3a+23Bfgl30xrKTQ7O1EQIjhPDBtdN/N6tQny7L42KbOYXUUGgLyq2weZMaC4j77b/nIcZ2L5UhlACJmKjeRQoP7O9bnLHxBwhG3DYZtu4fl8hRVcGa9jVEudslZJnev3jfW4NT6SpWRDj1WajmFLY4zNvcu0G+weHZ5aIFDSzQmERn0NwtwkyZ5TZbHahBOWd7bdtuXtJAwW91fWjIAbUbpoRFq6CxCwuyOaaBLl2NNy2HZ3B1wHk4haShZpfzqRtHKNdRHC4ajnoO9zcKc76WmZ+3qsOUMM6t4ttg2RQz6IVb9jboUoiYbll+hKHoNToVZKgt7BHL1bqL/0uL6oSWmtkyqWEOXcv7S0xKikx04554ApZzSDY5abOJM6i5l4ZusQBaZB7a0C5lEJE4Qo+Pj1rHi4jFugjwVa0kaIXYO4w2hFsEq2/rrp429cLpOAkL9Z37fCRllGkpYJOM9SuOuewg6laP9rcX85qY/F1UadrpQMM8BWg+sOxxSgVAH8dW5ayMrIBjh2zzM95FceBDdup6CHR1XDHWMAIXXA/cgwn28tkhAYi+BYPp6AWSw6zlb1Y=
  on:
    tags: true
    repo: EnlightNS/enlightns-cli
notifications:
  email: false
  slack:
    secure: C1LGF/oU/NbgZgPCOMQeh5A7AAWrL3s6QX/FdUWw91QjLfBLJYIyEDcWIw1N8KeiHsLelfUQh9feGJfQVHWjjmn4auNbbykFQC5N9BrKvD5F8IE61ck3YSck7leqNpB/GnNybbqHNJD2X6/su+oCBOhyk60XdFbBMIWTlch4cJRWbzymDFM86xIkR5pJhGZXmbj2RlXsrPPSoFKgHOjrfLQP0bACKhZnymkvMPQlm0CWIOeX6prv/8BAsAgEUOqnXCr1UQUVKcbxmDEQ1KCpyzH3jIl1aXG/wh/cp0uF+urYEfpTRDsbl21MiztMTJcqbHgC1fhhkNGhtNvCBAmNc3JpavF+iI4gHuUSRJa+tPGsPndMlNsqu3xwJ0gW2vGj8admdHEWIkK3P2GkqB8ZVK673mLYSo4c1beOU6kr55Tq2MPhSg+znq0cYN3/gDCoBqVmedA4qeG1NrBpvvHodBfRt6AM8Gyn1uQme+NXShf2ovNP0o3lGKyLx0b9vsnbf8bUH/a7wc0CeDTPWh5YNB+aXN/1mSnGmUS/Peu0vIuvcxe8ZXJfXjMFlFcyV0p/SyI5B0BGoIThgODZCqQBZiECoHfJvXv0Cvxsy4kLrdZssNpNVqAYGtQebnU486Y3Nx5aYKbnRFFZUMqx7AJ2nhG+FkNVkI7QAhtxo2ujgU0=
env:
  global:
    secure: JcVoz0BqRpkIqvp5137KqCeaVa9OpEriimS+csKigWb8t9CP1Pdoa3KrJCH+zzkjAqhVgHO4IrEPUKwx94FZN+jPzduRcqZ/IvuLwP54FoEvB6YqcXOffQdrAyvdP7kUdexuOqcqLwAieVsychbOa3JZ2UmoA05Jb/H/JU4FiHimfVbg9B+Qzz0dS9NHmchsQMkvGoaNInUBGHzA6JiZfqBked0lo42dFIKLrkHQQsnR8I68KSqT2MTxeaRR4EIPnq3EkV9ixqXYoCo6VC1OnpxrG7LwwHyJH0qDnGKVC3Hy40HqxIJPeRqogEGoBeqF5cVlkZneIZRl/EUeSmY1cdXQorAHYQHHeemAwtuAnYKi4qM9mWFj3dQF9czbbSTSg6l52xhanbzrdo6cVoqZ397+Fv7a5gOReLsxKOVI3u81CcOcB9ly1Fi88cmbOCipfwbYqh1lv5uTCWTtNNW/wvIbTqs6l9opduyxYA+OwRbLUY2i14pNvCp+nvk/opCZ481nIGrp2pEadaZ+80BjS4XdQHOHd+fFrQh3GBt6UZmSsVrAp4u+jMsBIKI/niFQGFb3rH+hpPHmwiA9GiN1Fb/9fmV7ThTRctvf4yCBLNGb9JLWDtxx6zritM7z7ct+8PLynINjgu1RM/edZWiaXo70kvbr1wAfhfItnTyKPEg=
