language: python
python:
- '2.6'
- '2.7'
script:
- make test
install:
- pip install .
deploy:
  provider: pypi
  user: d2s3admin
  password:
    secure: vF0XBoa9kLwimOT9jyaUYhJ8uAmq0sPa4bRXtlV+01LL7WJDh5GIdQMn5T2nCW4kS1/qqia68tXlvf7f5eU7oINnh0cALyaOXSoe2oF9zpIJEXx8eMUDZPBAK2uDvVOan3Wb7i/n8KF1YU4E9KG4pGp9A3E50srKeG9FJdV2sl6JqRKUUxACow78Syq+JAqhZfIaXVUYxVwW1cuqp16hN8FU3xPUqCA1RYyl4orP52xTkDs7HjzwHCS7MPsccoABEOJfnNKcTluqLR4nCrpBl2a6T6PjENWTNCKggVjcQmuwBVFp0jRk3PHpYt7o6VZlA8vYFg7zqolecpP1MvLTHdH11WJJI60BTTYWx5GglugHF8x4Q3F4TZJTzYxoRSCyWxEtlZJ3nmbH07irHKoYb4rjG2zFUAGfqVPWeoye7uBXywOw/IE6Z7kryQUNXeOoRYQkqOogiZUD7jOgCuWCO5NMD+R9K2dSMNVcvXvdzzG4KfSZj4qkgo53u3OGEBTasiLPmpE5NR2Fk11eP3GzK3sL6cOyVNIl6vIENvNv5F25YsxbDNQSzbyXCa9uUy2tK7o52fLuMtp6JTrIoc8MGI/YOTi2ZXvgPnauFwgOAcvuQ/KBYrd35dwTXcUxeruXw3vvwtk0W4DPKb4sOK5efpU0gcm/tSR5duw0ypjtN7c=
  on:
    tags: true
    branch: master
notifications:
  email: false
  slack:
    secure: C1LGF/oU/NbgZgPCOMQeh5A7AAWrL3s6QX/FdUWw91QjLfBLJYIyEDcWIw1N8KeiHsLelfUQh9feGJfQVHWjjmn4auNbbykFQC5N9BrKvD5F8IE61ck3YSck7leqNpB/GnNybbqHNJD2X6/su+oCBOhyk60XdFbBMIWTlch4cJRWbzymDFM86xIkR5pJhGZXmbj2RlXsrPPSoFKgHOjrfLQP0bACKhZnymkvMPQlm0CWIOeX6prv/8BAsAgEUOqnXCr1UQUVKcbxmDEQ1KCpyzH3jIl1aXG/wh/cp0uF+urYEfpTRDsbl21MiztMTJcqbHgC1fhhkNGhtNvCBAmNc3JpavF+iI4gHuUSRJa+tPGsPndMlNsqu3xwJ0gW2vGj8admdHEWIkK3P2GkqB8ZVK673mLYSo4c1beOU6kr55Tq2MPhSg+znq0cYN3/gDCoBqVmedA4qeG1NrBpvvHodBfRt6AM8Gyn1uQme+NXShf2ovNP0o3lGKyLx0b9vsnbf8bUH/a7wc0CeDTPWh5YNB+aXN/1mSnGmUS/Peu0vIuvcxe8ZXJfXjMFlFcyV0p/SyI5B0BGoIThgODZCqQBZiECoHfJvXv0Cvxsy4kLrdZssNpNVqAYGtQebnU486Y3Nx5aYKbnRFFZUMqx7AJ2nhG+FkNVkI7QAhtxo2ujgU0=
